spring:
  application:
    name: springboot-01-demo
person:
  name: 张三
  age: 20
  birth-day: 2000/05/09 12:00:00
  like: true
  child:
    name: 李四
    age: 18
    birth-day: 2002/09/08 12:00:00
    text: ["haha", "hehe"]
  dogs:
    - name: 旺财1
      age: 1
    - name: 旺财2
      age: 2
    - { name: 旺财3, age: 3 }
  cats:
    bluecat:
      name: 蓝猫
      age: 1
    redcat:
      name: 红猫
      age: 2
    blackcat: {name: 黑猫, age: 3}